[package]
name = "squire-sqlite3-src"
description = "Bundled SQLite sources for Squire"
version = "3.53.0-alpha.2"
edition = "2024"
repository = "https://github.com/silverlyra/squire-src"
license = "Apache-2.0"
keywords = ["sqlite"]

include = [
    "/sqlite/README.md",
    "/sqlite/LICENSE.md",
    "/sqlite/VERSION",
    "/sqlite/sqlite3.c",
    "/sqlite/sqlite3.h",
    "/src",
    "/LICENSE.md",
    "/README.md",
]

[features]
default = []
parallel = ["cc/parallel"]

[dependencies.features]
package = "squire-sqlite3-features"
# path = "../../squire/crates/features"
version = "0.1.0-alpha.1"

[dependencies.cc]
version = "^1.2.34"

[workspace]
resolver = "2"
members = [".", "smoke"]
